# Generated by Django 5.2.12 on 2026-03-15 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.PositiveBigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('top_skills', models.JSONField(blank=True, default=list)),
                ('impact_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('ai_reasoning', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='members.member')),
                ('project_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_assignments', to='members.projectproposal')),
            ],
            options={
                'ordering': ['project_proposal_id', 'member_id'],
                'unique_together': {('member', 'project_proposal')},
            },
        ),
    ]
