# Generated by Django 5.2.12 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_member_user_project_projectmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="organization_login",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="roles",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
