# Generated by Django 5.2.12 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_member_organization_login_member_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="commits_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="member",
            name="github_token",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="member",
            name="issues_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="member",
            name="prs_merged_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="member",
            name="reviews_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
