# Generated by Django 5.2.12 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_member_contribution_fields_and_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectproposal",
            name="initiatives",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="projectproposal",
            name="overall_strategy",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="projectproposal",
            name="required_dna",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="projectproposal",
            name="technical_tips",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
