# Generated by Django 5.2.12 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_projectproposal_ai_detail_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="analysis_message",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="member",
            name="analysis_progress",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="member",
            name="analysis_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("READY", "Ready"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="is_analyzing",
            field=models.BooleanField(default=False),
        ),
    ]
